### ISSUE TITLE
SQL injections

### ISSUE THREAD

**Issue by Xander1233** [MCmoderSD/YEPPBot#13]
Since there is no escaping nor cleaning up of args, SQL injection might be possible with multiple commands.

Either escape all args, when inserting/doing any database queries, or remove all bad keywords, like DELETE, DROP, etc.

Escaping is probably the easier solution. You can either delete all `"` and `'` or you escape them with `\`, but keep in mind that you should then also escape all `\`, by writing `\\` (replace all `\` with `\\`).

For example:
1.
Argument: `random"; DROP TABLE quotes;`
Escaped: `random\"; DROP TABLE quotes;`

2.
Argument: `random\"; DROP TABLE quotes;`
Escaped: `random\\\"; DROP TABLE quotes;` (One escaping backslash for the user provided backslash, and one for escaping backslash for the " => \\\)

**Comment by MCmoderSD** [comment]
This issue is not applicable as I'm exclusively using Java’s PreparedStatement for database interactions, and all inputs are set using setString rather than being directly inserted into the SQL query. Prepared statements automatically handle escaping, which prevents SQL injection risks.
